### ISSUE TITLE
malloc error every time

### ISSUE THREAD

**Issue by UniekLee** [albertodebortoli/GoldRaccoon#16]
Hi guys

I'm trying to write an FTP performance test using GoldRaccoon. But I'm finding that I am getting an error stating:
`malloc: *** error for object 0x48ba000: pointer being freed was not allocated` 

I've tried setting a `malloc_error_break` breakpoint as XCode suggests, but it isn't giving me any help.

I don't know what information you'd need to help out with this. I can post the whole class, just let me know if that would help?

I have implemented @t-oginogin's solution in issue #15 in hopes that it would help, but I think this is a separate issue that I'm getting.

**Comment by albertodebortoli** [comment]
@UniekLee FYI #15 has been merged into master.

**Comment by UniekLee** [comment]
Turns out this wasn't an issue with GoldRacoon at all - it was an issue with my file handling between download and upload.
