### ISSUE TITLE
Still crashes when uploading files

### ISSUE THREAD

**Issue by ghost** [albertodebortoli/GoldRaccoon#17]
014-08-22 18:27:20.684 Meety[4223:60b] FAIL: Error Domain=com.albertodebortoli.goldraccoon Code=-1000 "The operation couldn’t be completed. (com.albertodebortoli.goldraccoon error -1000.)" UserInfo=0x9353ba0 {message=Not logged in.}

Code not necessary - it follows demo example.

**Comment by albertodebortoli** [comment]
This is not a crash, not even a crash log.
It simply means that the request failed and the reason is pretty clear: 530 FTP server error code.

**Comment by ghost** [comment]
The fact is is that it would fail to upload every now and then. I am now using NMSSH and have had zero issues.
