### ISSUE TITLE
Crash when upload file.

### ISSUE THREAD

**Issue by tranngoclinh88** [albertodebortoli/GoldRaccoon#2]
Hi Alberto.
I tried uploading a file each 1 minutes. It crashed very often. Here is the image for detail.

![screen shot 2013-12-29 at 11 01 54 pm](https://f.cloud.github.com/assets/1511264/1819592/a0f694fe-70a2-11e3-9e79-374a8c5424e3.png)

**Comment by albertodebortoli** [comment]
Hi @tranngoclinh88, can you please share some code you wrote?

**Comment by dani-mp** [comment]
Hello there. I've been having a similar problem: I upload a file to my FTP and not always but very often, some seconds later the app crashes, showing the same as @tranngoclinh88 posted.

This is my code:

```
- (void)uploadFileWithPath:(NSString *)filePath toFTP:(FTP *)ftp withName:(NSString *)fileName andCompletionBlock:(BooleanResponseBlock)completionBlock {
    self.requestsManager = [[GRRequestsManager alloc] initWithHostname:ftp.host user:ftp.user password:ftp.password];
    self.requestsManager.delegate = self;
    self.uploadFileCompletionBlock = completionBlock;
    [self.requestsManager addRequestForUploadFileAtLocalPath:filePath toRemotePath:[NSString stringWithFormat:@"%@/%@", ftp.folder, fileName]];
    [self.requestsManager startProcessingRequests];
}

- (void)requestsManager:(id<GRRequestsManagerProtocol>)requestsManager didCompleteUploadRequest:(id<GRDataExchangeRequestProtocol>)request {
    self.uploadFileCompletionBlock(nil, YES);
}

- (void)requestsManager:(id<GRRequestsManagerProtocol>)requestsManager didFailRequest:(id<GRRequestProtocol>)request withError:(NSError *)error {
    self.uploadFileCompletionBlock(nil, NO);
}
```

Regards.

**Comment by jonasbark** [comment]
I'm getting it everytime at GRStreamInfo openWrite Line 103.
`CFWriteStreamSetProperty(writeStreamRef, kCFStreamPropertyShouldCloseNativeSocket, kCFBooleanTrue);` 

EDIT: apparently paths inside subfolders containing spaces aren't escaped properly. The fullURL method of GRRequest class returned nil as it tried to convert "ftp://xxx.com/1/xx xx.jpg" to NSURL which failed.
Inserting `path = [path stringByReplacingOccurrencesOfString:@" " withString:@"%20"];` fixed this.

**Comment by albertodebortoli** [comment]
@tranngoclinh88 @jonasbark are you still getting this crash with version 1.0.2 (with #15 merged in)?

**Comment by tranngoclinh88** [comment]
@albertodebortoli Thank you. I'll check carefully.
