### ISSUE TITLE
download the file name of chinese ,error

### ISSUE THREAD

**Issue by whoisLD** [albertodebortoli/GoldRaccoon#9]
i think is the encoding error,because when i show the file list ，the file name of chinese is
changing to unicode string like '\U00a1\U00a2\U03c0' , but when i decode the unicode string is wrong string . could you find the cause of error. thx

**Comment by albertodebortoli** [comment]
Please rephrase properly and provide a detailed description.

**Comment by albertodebortoli** [comment]
Closing as pointless.
